name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm ci

      - name: Build frontend
        run: npm run build
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}

      - name: Deploy to server
        env:
          SSH_KEY: ${{ secrets.EC2_SSH_KEY }}   # your EC2 private key stored as a secret
        run: |
          # Create the key file on the runner
          printf "%s\n" "$SSH_KEY" > ~/ec2_key.pem
          chmod 400 ~/ec2_key.pem

          # Use the key to rsync files to EC2
          rsync -avz -e "ssh -i ~/ec2_key.pem -o StrictHostKeyChecking=no" dist/ ubuntu@13.51.241.12:/var/www/frontend/

