name: Node.js CI & Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [20.x]   # Use a stable Node version

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Node
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Build frontend
      - name: Build frontend
        run: npm run build
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}  # Secret used at build time

      # 5. Deploy to EC2
      - name: Deploy to EC2
        env:
          SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          # Write private key to temp file
          printf "%s\n" "$SSH_KEY" > $RUNNER_TEMP/ec2_key.pem
          chmod 400 $RUNNER_TEMP/ec2_key.pem

          # Ensure the target directory exists
          ssh -i $RUNNER_TEMP/ec2_key.pem -o StrictHostKeyChecking=no ubuntu@13.51.241.12 "mkdir -p ~/frontend"

          # Sync files
          rsync -avz --delete -e "ssh -i $RUNNER_TEMP/ec2_key.pem -o StrictHostKeyChecking=no" dist/ ubuntu@13.51.241.12:~/frontend/

          # Optional: clean up the key
          rm -f $RUNNER_TEMP/ec2_key.pem
